### ISSUE TITLE
DIDMan: panic during organisation search

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1145]
```
echo: http: panic serving 172.19.0.5:41744: runtime error: slice bounds out of range [2:1]
goroutine 61562 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x14ce840, 0xc0015a4198})
	/usr/local/go/src/runtime/panic.go:844 +0x258
golang.org/x/text/transform.String({0x1826230, 0xc0000a8c00}, {0x21054e0, 0x1})
	/pkg/mod/golang.org/x/text@v0.3.7/transform/transform.go:650 +0xbe5
gopkg.in/Regis24GmbH/go-diacritics%2ev1.Normalize({0x21054e0?, 0xc0018ce998?})
	/pkg/mod/gopkg.in/!regis24!gmb!h/go-diacritics.v1@v1.0.0/diacritics.go:197 +0x5a
github.com/Regis24GmbH/go-phonetics.NewPhoneticCode({0x21054e0?, 0xc000aea137?})
	/pkg/mod/github.com/!regis24!gmb!h/go-phonetics@v1.0.0/phonetics.go:19 +0x38
github.com/nuts-foundation/nuts-node/vcr.CologneTransformer({0x18273b0?, 0xc00133d9c0?})
	/go/vcr/phonetics.go:31 +0x6c
github.com/nuts-foundation/go-leia/v3.fieldIndexer.Transform(...)
	/pkg/mod/github.com/nuts-foundation/go-leia/v3@v3.1.2/index_part.go:105
github.com/nuts-foundation/go-leia/v3.prefixPart.Condition({{0x1823700?, 0xc001db31b8?}, {0x18273b0?, 0xc00133d9c0?}}, {0x7ff3ea6258aa, 0x4, 0x2?}, 0xc000bdcd20?)
	/pkg/mod/github.com/nuts-foundation/go-leia/v3@v3.1.2/search.go:238 +0x45
github.com/nuts-foundation/go-leia/v3.findR(0x20?, {0x21a3778, 0x0, 0x0}, {0xc000ad83c0, 0x2, 0x2}, 0x7ff3ea8513a8?, {0xc0018cec58, 0x0, ...})
	/pkg/mod/github.com/nuts-foundation/go-leia/v3@v3.1.2/index.go:357 +0x2fb
github.com/nuts-foundation/go-leia/v3.(*index).Iterate(0xc0008acb80, 0xc001901920?, {{0xc0007bcee0?, 0xc0007bcf00?, 0xc0003f14f0?}}, 0x1823700?)
	/pkg/mod/github.com/nuts-foundation/go-leia/v3@v3.1.2/index.go:280 +0x1b2
github.com/nuts-foundation/go-leia/v3.resultScanQueryPlan.execute.func1(0xc000185340)
	/pkg/mod/github.com/nuts-foundation/go-leia/v3@v3.1.2/plan.go:136 +0x129
go.etcd.io/bbolt.(*DB).View(0xc0008acb80?, 0xc001360e10)
	/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:772 +0x82
github.com/nuts-foundation/go-leia/v3.resultScanQueryPlan.execute({{0xc0003f14f0, {{0xc0007bcee0, 0x2, 0x2}}}, {0x1831210, 0xc0008acb80}}, 0xc0007bcf00)
	/pkg/mod/github.com/nuts-foundation/go-leia/v3@v3.1.2/plan.go:117 +0xf8
github.com/nuts-foundation/go-leia/v3.(*collection).Iterate(0x20?, {{0xc0007bcee0?, 0x1?, 0xc000c75d40?}}, 0xc001360f80?)
	/pkg/mod/github.com/nuts-foundation/go-leia/v3@v3.1.2/collection.go:242 +0x38
github.com/nuts-foundation/go-leia/v3.(*collection).Find(0xc000636100?, {0x182ac58?, 0xc00085c600}, {{0xc0007bcee0?, 0x3?, 0xc001360ff0?}})
	/pkg/mod/github.com/nuts-foundation/go-leia/v3@v3.1.2/collection.go:230 +0xfa
github.com/nuts-foundation/nuts-node/vcr.(*vcr).Search(0xc0001e04b0, {0x182ac58, 0xc00085c600}, {0xc001b29d50, 0x2, 0x4268b2?}, 0x1?, 0xc000f46330?)
	/go/vcr/search.go:74 +0x10e
github.com/nuts-foundation/nuts-node/didman.(*didman).SearchOrganizations(0xc0003bc960, {0x182ac58, 0xc00085c600}, {0xc000aea137, 0x1}, 0xc00133d9a0)
	/go/didman/didman.go:291 +0x19d
github.com/nuts-foundation/nuts-node/didman/api/v1.(*Wrapper).SearchOrganizations(0xc000361d30, {0x1839cc8, 0xc001be3720}, {{0xc000aea137?, 0xe?}, 0xc00133d9a0?})
	/go/didman/api/v1/api.go:289 +0x9c
github.com/nuts-foundation/nuts-node/didman/api/v1.(*ServerInterfaceWrapper).SearchOrganizations(0xc000a53a00, {0x1839cc8, 0xc001be3720})
	/go/didman/api/v1/generated.go:1553 +0x37e
github.com/nuts-foundation/nuts-node/didman/api/v1.RegisterHandlersWithBaseURL.func8({0x1839cc8, 0xc001be3720})
	/go/didman/api/v1/generated.go:1643 +0x7f
github.com/labstack/echo/v4.(*Echo).add.func1({0x1839cc8, 0xc001be3720})
	/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:520 +0x51
github.com/nuts-foundation/nuts-node/core.loggerMiddleware.func1.1({0x1839cc8, 0xc001be3720})
	/go/core/echo.go:223 +0x85
github.com/nuts-foundation/nuts-node/core.DecodeURIPath.func1({0x1839cc8, 0xc001be3720})
	/go/core/engine.go:242 +0xd6
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000a2cd80, {0x1829b70?, 0xc000185260}, 0xc000a38000)
	/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:630 +0x3bc
net/http.serverHandler.ServeHTTP({0xc001901740?}, {0x1829b70, 0xc000185260}, 0xc000a38000)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc001be3680, {0x182ad00, 0xc000a82750})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db
```

**Comment by woutslakhorst** [comment]
The panic occurs very low-level:

```golang.org/x/text/transform.String({0x1826230, 0xc0000a8c00}, {0x21054e0, 0x1})
	/pkg/mod/golang.org/x/text@v0.3.7/transform/transform.go:650 +0xbe5```

We need the exact conditions on when this occurs. There could be a case that the used phonetics library can't handle certain input strings

**Comment by woutslakhorst** [comment]
We're using an outdated version of the diacretics/phonetics lib. A version 2 is available which does not use the string.Transform

**Comment by reinkrul** [comment]
My VCR's credentials DB:
[credentials.db.zip](https://github.com/nuts-foundation/nuts-node/files/8761850/credentials.db.zip)

**Comment by woutslakhorst** [comment]
@reinkrul can you confirm the fix?

**Comment by reinkrul** [comment]
It occurred on my cloud node which is running v2, will have to test when upgrading to master.

**Comment by woutslakhorst** [comment]
I assume it's solved now
