### ISSUE TITLE
BBolt panic on Microsoft Azure

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1236]
```
time="2022-07-04T11:13:41Z" level=debug msg="Configuring Network" module=core
unexpected fault address 0x7fbeb8d43008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fbeb8d43008 pc=0xc07846]

goroutine 1 [running]:
runtime.throw({0x157b713?, 0x30?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0005b1e48 sp=0xc0005b1e18 pc=0x438491
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:815 +0x125 fp=0xc0005b1e98 sp=0xc0005b1e48 pc=0x44e625
go.etcd.io/bbolt.(*freelist).read(0x157b4c0?, 0x5?)
	/pkg/mod/go.etcd.io/bbolt@v1.3.6/freelist.go:265 +0x26 fp=0xc0005b1f38 sp=0xc0005b1e98 pc=0xc07846
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
	/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:323 +0xae fp=0xc0005b1f68 sp=0xc0005b1f38 pc=0xc0296e
sync.(*Once).doSlow(0xc00015dcc8?, 0x10?)
	/usr/local/go/src/sync/once.go:68 +0xc2 fp=0xc0005b1fc8 sp=0xc0005b1f68 pc=0x4756c2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
go.etcd.io/bbolt.(*DB).loadFreelist(0xc00015db00?)
	/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:316 +0x47 fp=0xc0005b1ff8 sp=0xc0005b1fc8 pc=0xc02887
go.etcd.io/bbolt.Open({0xc0001e6da0, 0x1e}, 0x1bb800?, 0x2134fe0)
	/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:293 +0x46b fp=0xc0005b30d0 sp=0xc0005b1ff8 pc=0xc025eb
github.com/nuts-foundation/nuts-node/network/dag.NewState({0xc00010ed40?, 0xc00037f580?}, {0xc00002f590, 0x3, 0x3})
	/go/network/dag/state.go:73 +0x15d fp=0xc0005b31e8 sp=0xc0005b30d0 pc=0xe89f3d
github.com/nuts-foundation/nuts-node/network.(*Network).Configure(0xc00049e380, {{0xc00010edb8, 0x5}, {0x157a6aa, 0x4}, 0x0, {0xc00010ed40, 0xe}, {{{0xc00010ef50, 0x5}, ...}, ...}, ...})
	/go/network/network.go:115 +0x108 fp=0xc0005b3930 sp=0xc0005b31e8 pc=0x1181d28
github.com/nuts-foundation/nuts-node/core.(*System).Configure.func1({0x1512d20, 0xc00049e380})
	/go/core/engine.go:128 +0x15d fp=0xc0005b3a78 sp=0xc0005b3930 pc=0x9a5edd
github.com/nuts-foundation/nuts-node/core.(*System).VisitEnginesE(...)
	/go/core/engine.go:161
github.com/nuts-foundation/nuts-node/core.(*System).Configure(0xc000498640?)
	/go/core/engine.go:124 +0x1fb fp=0xc0005b3b38 sp=0xc0005b3a78 pc=0x9a5d3b
github.com/nuts-foundation/nuts-node/cmd.startServer({0x181fd90, 0xc000498600}, 0xc000498640)
	/go/cmd/root.go:117 +0x1d2 fp=0xc0005b3d30 sp=0xc0005b3b38 pc=0x12696d2
github.com/nuts-foundation/nuts-node/cmd.createServerCommand.func1(0xc0003ac500, {0x157a2d2?, 0x0?, 0x0?})
	/go/cmd/root.go:101 +0x4f fp=0xc0005b3d60 sp=0xc0005b3d30 pc=0x126948f
github.com/spf13/cobra.(*Command).execute(0xc0003ac500, {0x218e040, 0x0, 0x0})
	/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c fp=0xc0005b3e38 sp=0xc0005b3d60 pc=0x86a6dc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000123680)
	/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4 fp=0xc0005b3ef0 sp=0xc0005b3e38 pc=0x86ad54
github.com/spf13/cobra.(*Command).Execute(...)
	/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/nuts-foundation/nuts-node/cmd.Execute({0x181fd90?, 0xc000498600}, 0xc00049d820?)
	/go/cmd/root.go:240 +0x9f fp=0xc0005b3f10 sp=0xc0005b3ef0 pc=0x126c41f
main.main()
	/go/main.go:36 +0xac fp=0xc0005b3f80 sp=0xc0005b3f10 pc=0x126c8cc
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc0005b3fe0 sp=0xc0005b3f80 pc=0x43abb2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0005b3fe8 sp=0xc0005b3fe0 pc=0x46b1e1

goroutine 8 [select]:
io.(*pipe).read(0xc0001bcd20, {0xc000224000, 0x1000, 0x1?})
	/usr/local/go/src/io/pipe.go:57 +0xb1
io.(*PipeReader).Read(0x0?, {0xc000224000?, 0x0?, 0x0?})
	/usr/local/go/src/io/pipe.go:136 +0x25
bufio.(*Scanner).Scan(0xc00022af28)
	/usr/local/go/src/bufio/scan.go:215 +0x865
github.com/sirupsen/logrus.(*Entry).writerScanner(0x0?, 0xc0001001e8, 0xc00042c560)
	/pkg/mod/github.com/sirupsen/logrus@v1.8.1/writer.go:59 +0xa5
created by github.com/sirupsen/logrus.(*Entry).WriterLevel
	/pkg/mod/github.com/sirupsen/logrus@v1.8.1/writer.go:51 +0x3d1

goroutine 21 [syscall]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:151 +0x2f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x2a

goroutine 22 [select]:
os/signal.NotifyContext.func1()
	/usr/local/go/src/os/signal/signal.go:288 +0x70
created by os/signal.NotifyContext
	/usr/local/go/src/os/signal/signal.go:287 +0x165
2022-07-04T11:13:41.9930076Z stderr F 
```

The network database is located on Azure Fileshare storage.

**Comment by reinkrul** [comment]
Maybe it doesn't play nicely with memory mapped files?
https://github.com/prometheus/prometheus/issues/10892

SMB is used; which appearantely doesn't play very nice with MMAP; https://serverfault.com/questions/305556/how-do-i-speed-up-memory-mapped-files-over-network

Use of NFS should be attempted.

**Comment by reinkrul** [comment]
We might want to log the filesystem type like they do in Prometheus (OS-specific, though);

https://github.com/prometheus/prometheus/blob/26117fc8850f36d6018b01c54d84df16859467e9/util/runtime/statfs_default.go#L25

**Comment by gerardsn** [comment]
Does not seem to be an issue anymore since we have not had anyone mention this or ask questions about it in months. Closing for now, but can be reopened with more details on the issue if it still persists.
