### ISSUE TITLE
Crypto: Vault adapter causes panic/nil deref

### ISSUE THREAD

**Issue by JoeriLandman** [nuts-foundation/nuts-node#1407]
```
echo: http: panic serving 127.0.0.1:50866: runtime error: invalid memory address or nil pointer dereference
goroutine 102652 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x1508b40, 0x2369960})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/nuts-foundation/nuts-node/crypto/storage.vaultKVStorage.getValue({{{0xc00004a018, 0x5f}, {0xc0000442da, 0x22}, {0xc00004431d, 0x1e}, 0x12a05f200}, {0x199bc70, 0xc000128088}}, {0xc00009abe0, ...}, ...)
	/go/crypto/storage/vault.go:132 +0xc2
github.com/nuts-foundation/nuts-node/crypto/storage.vaultKVStorage.GetPrivateKey({{{0xc00004a018, 0x5f}, {0xc0000442da, 0x22}, {0xc00004431d, 0x1e}, 0x12a05f200}, {0x199bc70, 0xc000128088}}, {0xc000a70e80, ...})
	/go/crypto/storage/vault.go:116 +0xfd
github.com/nuts-foundation/nuts-node/crypto.(*Crypto).SignJWT(0xc0015516c4?, 0x4?, {0xc000a70e80, 0x61})
	/go/crypto/jwx.go:53 +0x3a
github.com/nuts-foundation/nuts-node/auth/services/oauth.(*service).CreateJwtGrant(0xc0003583f0, {{0xc0015516c0, 0x35}, {0xc001551680, 0x35}, 0x0, {0xc00063e3c0, 0x12}, {0x23cfa48, 0x0, ...}})
	/go/auth/services/oauth/oauth.go:457 +0x2f0
github.com/nuts-foundation/nuts-node/auth/api/v1.Wrapper.RequestAccessToken({{0x199e978?, 0xc0003b47e0?}, {0x7f40936ef8e0?, 0xc0003b46c0?}}, {0x19aee08, 0xc00082ea00})
	/go/auth/api/v1/api.go:299 +0x198
github.com/nuts-foundation/nuts-node/auth/api/v1.(*ServerInterfaceWrapper).RequestAccessToken(...)
	/go/auth/api/v1/generated.go:1822
github.com/nuts-foundation/nuts-node/auth/api/v1.RegisterHandlersWithBaseURL.func5({0x19aee08, 0xc00082ea00})
	/go/auth/api/v1/generated.go:1959 +0x8a
github.com/labstack/echo/v4.(*Echo).add.func1({0x19aee08, 0xc00082ea00})
	/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:520 +0x51
github.com/labstack/echo-contrib/prometheus.(*Prometheus).HandlerFunc.func1({0x19aee08, 0xc00082ea00})
	/pkg/mod/github.com/labstack/echo-contrib@v0.13.0/prometheus/prometheus.go:406 +0x230
github.com/labstack/echo/v4/middleware.RateLimiterWithConfig.func1.1({0x19aee08, 0xc00082ea00})
	/pkg/mod/github.com/labstack/echo/v4@v4.7.2/middleware/rate_limiter.go:132 +0x16f
github.com/nuts-foundation/nuts-node/core.loggerMiddleware.func1.1({0x19aee08, 0xc00082ea00})
	/go/core/echo.go:236 +0x85
github.com/nuts-foundation/nuts-node/core.DecodeURIPath.func1({0x19aee08, 0xc00082ea00})
	/go/core/engine.go:243 +0xd6
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x19aee08, 0xc00082ea00})
	/pkg/mod/github.com/labstack/echo/v4@v4.7.2/middleware/cors.go:142 +0x470
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000375440, {0x199d320?, 0xc0003789a0}, 0xc0001b2800)
	/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:630 +0x3bc
net/http.serverHandler.ServeHTTP({0x199a328?}, {0x199d320, 0xc0003789a0}, 0xc0001b2800)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00082e960, {0x199e4e0, 0xc000995620})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db
```

**Comment by reinkrul** [comment]
- What version of Vault are you running?
- How often do you see it?
- Are there access token requests that do succeed? Or do they all fail?

**Comment by JoeriLandman** [comment]
vault version: pending
amount: about 4 times an hour
access tokens: no (or not yet), our index wont recover so we cannot hit the flow of access tokens yet

**Comment by reinkrul** [comment]
@JoeriLandman looks like your application tries to request an access token for a DID, for which it can't find the selected JWT signing key in Vault (assertionMethod in DID document). Can you assert that the assertionMethod keys in the DID document (for which the access token is created) is present in Vault?

**Comment by JoeriLandman** [comment]
everything in vault is there, but now that we have a working node again the error is gone. So I suspect some other file on disk to be missing to cause this.
