### ISSUE TITLE
Crypto: using Vault, PrivateKeyExists causes a panic when it doesn't exist

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#1459]
```
goroutine 1 [running]:
github.com/nuts-foundation/nuts-node/crypto/storage.vaultKVStorage.PrivateKeyExists({{{0xc000055618, 0x1a}, {0xc00004c01a, 0x32}, {0xc0000550dd, 0x21}, 0x12a05f200}, {0x199bc70, 0xc00000e080}}, {0xc0000d3a00, ...})
	/go/crypto/storage/vault.go:156 +0x91
github.com/nuts-foundation/nuts-node/crypto.(*Crypto).Exists(0xc0004db228?, {0xc0000d3a00?, 0xc00004c29e?})
	/go/crypto/crypto.go:153 +0x26
github.com/nuts-foundation/nuts-node/network.(*Network).validateNodeDID(0xc0000001e0, {{{0xc00004c299, 0x4}, {0xc00004c29e, 0x2c}, {0xc0002f8360, 0x1, 0x1}, {0x0, 0x0, ...}, ...}})
	/go/network/network.go:387 +0x2f0
github.com/nuts-foundation/nuts-node/network.(*Network).Start(0xc0000001e0)
	/go/network/network.go:296 +0x205
github.com/nuts-foundation/nuts-node/core.(*System).Start.func1({0x1676740, 0xc0000001e0})
	/go/core/engine.go:98 +0xda
github.com/nuts-foundation/nuts-node/core.(*System).VisitEnginesE(...)
	/go/core/engine.go:162
github.com/nuts-foundation/nuts-node/core.(*System).Start(0xc0001b0000?)
	/go/core/engine.go:95 +0x90
github.com/nuts-foundation/nuts-node/cmd.startServer({0x199f0b0, 0xc000489300}, 0xc0001b0000)
	/go/cmd/root.go:143 +0x3be
github.com/nuts-foundation/nuts-node/cmd.createServerCommand.func1(0xc00054b680, {0x16e654e?, 0x0?, 0x0?})
	/go/cmd/root.go:104 +0x56
github.com/spf13/cobra.(*Command).execute(0xc00054b680, {0x23cfa48, 0x0, 0x0})
	/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000fa000)
	/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
github.com/nuts-foundation/nuts-node/cmd.Execute({0x199f0b0?, 0xc000489300}, 0xc0001b2720?)
	/go/cmd/root.go:256 +0x9f
main.main()
	/go/main.go:36 +0xac
```

**Comment by reinkrul** [comment]
Also backport to v4

**Comment by reinkrul** [comment]
Similar to https://github.com/nuts-foundation/nuts-node/issues/1407

**Comment by stevenvegt** [comment]
Also, check other situations which might trigger this.
