### ISSUE TITLE
Panic during performance test

### ISSUE THREAD

**Issue by gerardsn** [nuts-foundation/nuts-node#1543]
running performance test: networks/redis on current master

```
time="2022-10-12T09:48:38Z" level=error msg="IssueVC failed" error="unable to publish the issued credential: failed to publish credential, error while creating transaction: unable to add newly created transaction to State: unable to obtain Redis transaction-level write lock: Database Error: redsync: failed to acquire lock" module=VCR operation=IssueVC operationID=IssueVC requestURI=/internal/vcr/v2/issuer/vc user="<nil>"
time="2022-10-12T09:48:38Z" level=error msg="IssueVC failed" error="unable to publish the issued credential: failed to publish credential, error while creating transaction: unable to add newly created transaction to State: unable to obtain Redis transaction-level write lock: Database Error: 1 error occurred:\n\t* context deadline exceeded\n\n" module=VCR operation=IssueVC operationID=IssueVC requestURI=/internal/vcr/v2/issuer/vc user="<nil>"
echo: http: panic serving 172.21.0.11:49920: runtime error: invalid memory address or nil pointer dereference
goroutine 679510 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0x1577180, 0x2436eb0})
        /usr/local/go/src/runtime/panic.go:890 +0x262
github.com/nuts-foundation/nuts-node/network.(*Network).calculateLamportClock(0xc0001a2300, {0x1a27ec0, 0xc000044030}, {0xc0150bc300?, 0x2, 0x1a27ec0?})
        /go/network/network.go:544 +0xfd
github.com/nuts-foundation/nuts-node/network.(*Network).CreateTransaction(0xc0001a2300, {{0x1a27280, 0xc012dafa60}, {0xc0200c3200, 0x477, 0x480}, {0x17736b7, 0x13}, 0x0, {0x32cb50b8, ...}, ...})
        /go/network/network.go:497 +0xa2b
github.com/nuts-foundation/nuts-node/vcr/issuer.networkPublisher.PublishCredential({{_, _}, {_, _}, {_, _}, {_, _}}, {{0xc014802900, 0x3, ...}, ...}, ...)
        /go/vcr/issuer/network_publisher.go:101 +0x595
github.com/nuts-foundation/nuts-node/vcr/issuer.issuer.Issue({{_, _}, {_, _}, {_, _}, _, {_, _}}, {{0xc014d30480, ...}, ...}, ...)
        /go/vcr/issuer/issuer.go:92 +0x4bd
github.com/nuts-foundation/nuts-node/vcr/api/v2.Wrapper.IssueVC({{0x0, 0x0}, {0x1a1d8a0, 0xc000297320}, {0x1a2ffb8, 0xc0002a4b40}}, {0x1a3eff8, 0xc011ab5720})
        /go/vcr/api/v2/api.go:138 +0x30b
github.com/nuts-foundation/nuts-node/vcr/api/v2.(*ServerInterfaceWrapper).IssueVC(0xc000305f60, {0x1a3eff8, 0xc011ab5720})
        /go/vcr/api/v2/generated.go:1932 +0x8f
github.com/nuts-foundation/nuts-node/vcr/api/v2.RegisterHandlersWithBaseURL.func2({0x1a3eff8, 0xc011ab5720})
        /go/vcr/api/v2/generated.go:2143 +0x7f
github.com/labstack/echo/v4.(*Echo).add.func1({0x1a3eff8, 0xc011ab5720})
        /pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x51
github.com/labstack/echo-contrib/prometheus.(*Prometheus).HandlerFunc.func1({0x1a3eff8, 0xc011ab5720})
        /pkg/mod/github.com/labstack/echo-contrib@v0.13.0/prometheus/prometheus.go:406 +0x230
github.com/labstack/echo/v4/middleware.RequestLoggerConfig.ToMiddleware.func1.1({0x1a3eff8, 0xc011ab5720})
        /pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/request_logger.go:219 +0x168
github.com/nuts-foundation/nuts-node/http.decodeURIPath.func1({0x1a3eff8, 0xc011ab5720})
        /go/http/engine.go:212 +0xd6
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0000cdb00, {0x1a26b60?, 0xc021e09340}, 0xc008d0ca00)
        /pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x3d1
net/http.serverHandler.ServeHTTP({0x1a23b40?}, {0x1a26b60, 0xc021e09340}, 0xc008d0ca00)
        /usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc011ee7c20, {0x1a27f30, 0xc000846e40})
        /usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3102 +0x4db
time="2022-10-12T09:48:38Z" level=warning msg="Conn has unread data" module=Storage
time="2022-10-12T09:48:38Z" level=error msg="IssueVC failed" error="unable to publish the issued credential: failed to publish credential, error while creating transaction: unable to add newly created transaction to State: unable to obtain Redis transaction-level write lock: Database Error: redsync: failed to acquire lock" module=VCR operation=IssueVC operationID=IssueVC requestURI=/internal/vcr/v2/issuer/vc user="<nil>"
```

**Comment by reinkrul** [comment]
Panic is caused by clock shelf having a TX ref which points to a non-existent TX

`network/dag/dag.go:451`:

```
transactions := tx.GetShelfReader(transactionsShelf)
transactionBytes, err := transactions.Get(stoabs.NewHashKey(hash))
if err != nil || transactionBytes == nil {
   return nil, err
}
```

**Comment by reinkrul** [comment]
Similar nil derefence:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1318a5c]

goroutine 841428 [running]:
github.com/nuts-foundation/nuts-node/network/transport/v2.(*protocol).collectTransactionList(0xc000214300, {0x1a27ec0, 0xc000044030}, {0xc000a30000?, 0x2d2, 0x4?})
	/go/network/transport/v2/handlers.go:380 +0xfc
github.com/nuts-foundation/nuts-node/network/transport/v2.(*protocol).handleTransactionRangeQuery(0xc000214300, {{0xc000238fc0, 0x24}, {0xc00036aef0, 0x10}, {{{0xc0000c0204, 0x4}, {0xc0000c0209, 0x2c}, {0xc000304b20, ...}, ...}}, ...}, ...)
	/go/network/transport/v2/handlers.go:250 +0x24e
github.com/nuts-foundation/nuts-node/network/transport/v2.handleASync.func1()
	/go/network/transport/v2/handlers.go:77 +0x62
created by github.com/nuts-foundation/nuts-node/network/transport/v2.handleASync
	/go/network/transport/v2/handlers.go:76 +0xea
```

This one is caused by clock shelf having a TX ref which points to a non-existent TX

`network/dag/dag.go:451`:

```
transactions := tx.GetShelfReader(transactionsShelf)
transactionBytes, err := transactions.Get(stoabs.NewHashKey(hash))
if err != nil || transactionBytes == nil {
   return nil, err
}
```

**Comment by woutslakhorst** [comment]
All `getTransaction` paths should be checked if a nil return is checked and caught.
