### ISSUE TITLE
Fix race condition which causes failing tests

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-node#1943]
Shutdown order is wrong which causes a nil pointer error.

**Comment by gerardsn** [comment]
https://app.circleci.com/pipelines/github/nuts-foundation/nuts-node/5858/workflows/49db23dc-cecf-4faf-a544-1c1ee2e1b3a0/jobs/7959

```
=== RUN   TestVDRIntegration_ReprocessEvents
INFO[0000] Setting up FileSystem backend for storage of private key material. Discouraged for production use unless backups and encryption is properly set up. Consider using the Hashicorp Vault backend.  module=Crypto
DEBU[0000] Creating BBolt store                          module=Storage store=vdr/didstore
INFO[0000] Node DID not set, will be auto-discovered.    module=Network
WARN[0000] Not starting the payload scheduler as node DID is not set  module=Network
WARN[0000] TLS is disabled, which is only meant for demo/workshop purposes!  module=Network
DEBU[0000] Starting gRPC server on :5555                 module=Network
INFO[0000] TLS is disabled, this is very unsecure and only suitable for demo/development environments.  module=Network
DEBU[0000] Start connecting                              module=Network
INFO[0000] gRPC server started on :5555                  module=Network
INFO[0000] Assuming this is a new node, discovered NutsComm addresses are processed with a 5m0s delay  module=Network
INFO[0000] Starting reprocess of application/did+json    module=Network
DEBU[0000] Generated new key pair                        keyID="did:nuts:J3wxEELE4LuV2boyJkMEBbAidkkna23hmksiNN6RpJvB#_Vf5Wc2N17Y1k0Vj5fC53nqPKTVZCMGFLADOwNBsxyg" module=Crypto
AUDIT[0000] Generating new key pair: did:nuts:J3wxEELE4LuV2boyJkMEBbAidkkna23hmksiNN6RpJvB#_Vf5Wc2N17Y1k0Vj5fC53nqPKTVZCMGFLADOwNBsxyg  actor=test-actor event=CreateNewKey module=Crypto operation=TestModule.TestOperation
AUDIT[0000] Signing a JWS with key: did:nuts:J3wxEELE4LuV2boyJkMEBbAidkkna23hmksiNN6RpJvB#_Vf5Wc2N17Y1k0Vj5fC53nqPKTVZCMGFLADOwNBsxyg  actor=test-actor event=SignJWS module=Crypto operation=TestModule.TestOperation
DEBU[0000] Processing DID document received from Nuts Network  module=VDR txRef=9dd1f94cefeb51b29f203f81fad4b1eb0aea952760ab58bbfbe3a5d70432b600
DEBU[0000] Handling DID document creation                did="did:nuts:J3wxEELE4LuV2boyJkMEBbAidkkna23hmksiNN6RpJvB" module=VDR txRef=9dd1f94cefeb51b29f203f81fad4b1eb0aea952760ab58bbfbe3a5d70432b600
INFO[0000] DID document registered                       did="did:nuts:J3wxEELE4LuV2boyJkMEBbAidkkna23hmksiNN6RpJvB" module=VDR txRef=9dd1f94cefeb51b29f203f81fad4b1eb0aea952760ab58bbfbe3a5d70432b600
DEBU[0000] Stopping gRPC connection manager              module=Network
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe312c3]

goroutine 698 [running]:
github.com/nuts-foundation/nuts-node/crypto/storage/fs.fileSystemBackend.ListPrivateKeys.func1({0xc0000480b0?, 0xaa?}, {0x0, 0x0}, {0x4ab5a5?, 0x51867e?})
	/home/circleci/project/crypto/storage/fs/fs.go:135 +0x43
path/filepath.walk({0xc000020700, 0x3c}, {0x1c27ff0, 0xc00026a820}, 0xc0001f1eb0)
	/usr/local/go/src/path/filepath/path.go:454 +0x28f
path/filepath.Walk({0xc000020700, 0x3c}, 0xc0001f1eb0)
	/usr/local/go/src/path/filepath/path.go:521 +0x85
github.com/nuts-foundation/nuts-node/crypto/storage/fs.fileSystemBackend.ListPrivateKeys({{0xc000020700?, 0xc0004b34a8?}})
	/home/circleci/project/crypto/storage/fs/fs.go:134 +0x70
github.com/nuts-foundation/nuts-node/crypto/storage/spi.wrapper.ListPrivateKeys(...)
	/home/circleci/project/crypto/storage/spi/wrapper.go:81
github.com/nuts-foundation/nuts-node/crypto.(*Crypto).List(0xc00021c380)
	/home/circleci/project/crypto/crypto.go:130 +0x43
github.com/nuts-foundation/nuts-node/network/transport.(*autoNodeDIDResolver).Resolve(0xc0008e5140)
	/home/circleci/project/network/transport/nodedid.go:76 +0x364
github.com/nuts-foundation/nuts-node/network.(*Network).DiscoverServices(0xc0005c01e0, {{{0xc00045a404, 0x4}, {0xc00045a409, 0x2c}, {0xc0003bcb00, 0x1, 0x1}, {0x0, 0x0, ...}, ...}})
	/home/circleci/project/network/network.go:306 +0x466
github.com/nuts-foundation/nuts-node/vdr.(*ambassador).callback(0xc000618960, {0x1c2da80, 0xc000ace0f0}, {0xc000b28000, 0x39f, 0x39f})
	/home/circleci/project/vdr/ambassador.go:190 +0x9b5
github.com/nuts-foundation/nuts-node/vdr.(*ambassador).handleReprocessEvent(0x483579?, 0xc00021c770)
	/home/circleci/project/vdr/ambassador.go:132 +0x565
github.com/nats-io/nats%2ego.(*js).subscribe.func1(0xc0003f9450?)
	/home/circleci/go/pkg/mod/github.com/nats-io/nats.go@v1.23.0/js.go:1641 +0x3b
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc000349200, 0xc0003f9450)
	/home/circleci/go/pkg/mod/github.com/nats-io/nats.go@v1.23.0/nats.go:2940 +0x783
created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked
	/home/circleci/go/pkg/mod/github.com/nats-io/nats.go@v1.23.0/nats.go:4171 +0x876
FAIL	github.com/nuts-foundation/nuts-node/vdr	0.833s
FAIL
```

**Comment by woutslakhorst** [comment]
`Shutdown` is handled in reverse order of `start`. The eventManager is started before crypto, seems wrong. Crypto can be started  as one of the first since it has the least dependencies?

**Comment by reinkrul** [comment]
Crypto engine can be started as 2nd engine, to have a more robust startup order. Might fix this. Trivial issue; only seen twice (now) in Github build.
