### ISSUE TITLE
Parallel DID creates/updates makes DAG walker panic

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#491]
Tested using https://github.com/nuts-foundation/nuts-node/blob/vdr-load-test/generate-loads-of-dids_test.go:

```
node_1   | time="2021-09-30T08:45:46Z" level=info msg="DID document updated (tx=b4325e9b57b090c67030b9f56350d49dbd5bce241deda8acf142e840f17c16c6,did=did:nuts:5bL9Qw9mdwSs7puyDi5xpycDfhstMb15E78VbhLfGphP)" module=VDR
node_1   | fatal error: concurrent map read and map write
node_1   |
node_1   | goroutine 111 [running]:
node_1   | runtime.throw({0xf563ff, 0xc000ed9d20})
node_1   | 	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc000ed9cf0 sp=0xc000ed9cc0 pc=0x4355b1
node_1   | runtime.mapaccess2(0xebc140, 0xc0015f1860, 0x99b631a1d9ad8401)
node_1   | 	/usr/local/go/src/runtime/map.go:469 +0x205 fp=0xc000ed9d30 sp=0xc000ed9cf0 pc=0x40e565
node_1   | github.com/nuts-foundation/nuts-node/network/dag.bfsWalkerAlgorithm.walk({0xc0002a5560, 0xc0002a5590}, 0xc000d05550, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
node_1   | 	/go/network/dag/bfswalker.go:56 +0x40e fp=0xc000ed9ee8 sp=0xc000ed9d30 pc=0xa66c6e
node_1   | github.com/nuts-foundation/nuts-node/network/dag.(*bfsWalkerAlgorithm).walk(0xc0004c4a00, 0xc0000b9440, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
node_1   | 	<autogenerated>:1 +0x55 fp=0xc000ed9f40 sp=0xc000ed9ee8 pc=0xa6c735
node_1   | github.com/nuts-foundation/nuts-node/network/dag.bboltDAG.Walk.func1(0x0)
node_1   | 	/go/network/dag/bbolt_dag.go:211 +0x182 fp=0xc000ed9fe8 sp=0xc000ed9f40 pc=0xa64302
node_1   | go.etcd.io/bbolt.(*DB).View(0xa1d851, 0xc000eda060)
node_1   | 	/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:772 +0x82 fp=0xc000eda050 sp=0xc000ed9fe8 pc=0xa1b802
node_1   | github.com/nuts-foundation/nuts-node/network/dag.bboltDAG.Walk({0xc0000b9440, {0xc00000e708, 0x1, 0x1}, {0xc000610e70, 0x3, 0x3}}, {0x10d6720, 0xc0004c4a00}, 0xc000d05550, ...)
node_1   | 	/go/network/dag/bbolt_dag.go:204 +0xc5 fp=0xc000eda0b0 sp=0xc000eda050 pc=0xa64105
node_1   | github.com/nuts-foundation/nuts-node/network/dag.(*bboltDAG).Walk(0xc0004468c0, {0x10d6720, 0xc0004c4a00}, 0x0, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
node_1   | 	<autogenerated>:1 +0xe5 fp=0xc000eda168 sp=0xc000eda0b0 pc=0xa6c445
node_1   | github.com/nuts-foundation/nuts-node/network/dag.(*replayingDAGPublisher).publish(0xc0002a55c0, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
node_1   | 	/go/network/dag/publisher.go:65 +0x90 fp=0xc000eda1c8 sp=0xc000eda168 pc=0xa69a10
node_1   | github.com/nuts-foundation/nuts-node/network/dag.(*replayingDAGPublisher).PayloadWritten(...)
node_1   | 	/go/network/dag/publisher.go:29
node_1   | github.com/nuts-foundation/nuts-node/network/dag.(*replayingDAGPublisher).PayloadWritten-fm({0xa1b700, 0xc00134cfe0})
node_1   | 	/go/network/dag/publisher.go:28 +0x34 fp=0xc000eda200 sp=0xc000eda1c8 pc=0xa6bc74
node_1   | github.com/nuts-foundation/nuts-node/network/dag.notifyObservers({0xc00000e710, 0x1, 0xc000eda300}, {0xebc140, 0xc00134cfe0})
node_1   | 	/go/network/dag/bbolt_dag.go:401 +0x43 fp=0xc000eda228 sp=0xc000eda200 pc=0xa66203
node_1   | github.com/nuts-foundation/nuts-node/network/dag.bboltPayloadStore.WritePayload({0xc0000b9440, {0xc00000e710, 0x110a3c8, 0xc0013a9930}}, {0x83, 0xfe, 0x76, 0xc1, 0xa8, 0xdc, ...}, ...)
node_1   | 	/go/network/dag/bbolt_payloadstore.go:52 +0x119 fp=0xc000eda2e8 sp=0xc000eda228 pc=0xa666b9
node_1   | github.com/nuts-foundation/nuts-node/network/dag.(*bboltPayloadStore).WritePayload(0xc0003941c0, {0x83, 0xfe, 0x76, 0xc1, 0xa8, 0xdc, 0xa4, 0x5c, 0x9, ...}, ...)
node_1   | 	<autogenerated>:1 +0x7a fp=0xc000eda350 sp=0xc000eda2e8 pc=0xa6c67a
node_1   | github.com/nuts-foundation/nuts-node/network.(*Network).CreateTransaction(0xc0001be400, {0xf4537c, 0x14}, {0xc00129f400, 0x10e6710, 0xc00}, {0x10e8a60, 0xc00041e1e0}, 0x0, {0xc04d7c2e930d7f74, ...}, ...)

(etc)
```

**Comment by reinkrul** [comment]
The problem is that `ReplayingDAGPublisher` is called (indirectly) from different actors (incoming network transactions, REST API creating/updating DIDs, etc) in parallel, but isn't synchronized in itself. It should probably be thread-safe.

**Comment by woutslakhorst** [comment]
There's also a nested bbolt read transaction going on which might produce some weird behaviour. bbolt transactions set 2 locks concurrently. To exclude nested transactions as a problem the db.View from `walk` and `readmany` should be prevented and then retested with the `vdr-load-test` branch

**Comment by woutslakhorst** [comment]
The nested db.View is definitely the problem

**Comment by reinkrul** [comment]
I'm not convinced nested reads are the problem, because BBolt uses an `RWMutex`: multiple readers but writers need exclusive lock. So when reading no writers can be active, and when writing no readers (or other writers) can be active. Otherwise it would mean you can read in parallel from BBolt?

So I don't think BBolt has something that explicitely breaks nested `View` TXs which seems improbable to me (since it would have to detect/work on a goroutine state/ID for recognizing/breaking nested calls), because parallel reads are supported.

I wrote a test for this:

```go
func TestBBoltConcurrency(t *testing.T) {
	t.Run("nested TX", func(t *testing.T) {
		db, _ := bbolt.Open("nested.db", os.ModePerm, nil)
		key := []byte("msg")
		value := []byte("Hello, World!")
		bucket := []byte("test")
		err := db.Update(func(tx *bbolt.Tx) error {
			b, _ := tx.CreateBucket(bucket)
			return b.Put(key, value)
		})
		if !assert.NoError(t, err) {
			return
		}
		err = db.View(func(tx *bbolt.Tx) error {
			return db.View(func(nestedTX *bbolt.Tx) error {
				assert.Equal(t, value, nestedTX.Bucket(bucket).Get(key))
				return nil
			})
		})
		assert.NoError(t, err)
	})
}
```

And it succeeds.

**Comment by reinkrul** [comment]
My hypothesis is that `View` is called from an `Update` call or vice versa (write lock is exclusive, so you'll cause a deadlock when trying to acquire read from a write transaction, the other way around is also true).

**Comment by reinkrul** [comment]
Nested view might actually be the cause of this but in a slightly different way:

Goroutine `1` is walking the DAG, calling `View()` for the first time. Then goroutine `2` tries to add a document to the DAG, trying to acquire a write lock (which is blocked because of the first `View()` call). Then goroutine `1` calls the nested `View()` which deadlocks because the write lock is being acquired.

`RWMutex.RLock` states:

```
// It should not be used for recursive read locking; a blocked Lock
// call excludes new readers from acquiring the lock. See the
// documentation on the RWMutex type.
```

**Comment by reinkrul** [comment]
Fixes the deadlock, the panic might still be there, will have to test and fix.
