### ISSUE TITLE
Panic in tests suggests race condition/missing mutex

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/nuts-node#664]
CircleCI reports the following:

```
time="2021-12-07T12:35:09Z" level=info msg="Stopping gRPC connection manager" module=Network
time="2021-12-07T12:35:09Z" level=info msg="Stopping gRPC connection manager" module=Network
time="2021-12-07T12:35:09Z" level=warning msg="*v2.protocol: Failed to open gRPC stream (addr=localhost:6162): rpc error: code = Canceled desc = grpc: the client connection is closing" module=Network
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xd4aed0]

goroutine 345 [running]:
github.com/nuts-foundation/nuts-node/network/transport/grpc.(*grpcConnectionManager).openOutboundStreams(0xc000410540, {0x10afa88, 0xc000296460}, 0xc00039b400)
	/home/circleci/project/network/transport/grpc/connection_manager.go:232 +0x170
github.com/nuts-foundation/nuts-node/network/transport/grpc.grpcConnectionManager.Connect.func1(0xc000296488)
	/home/circleci/project/network/transport/grpc/connection_manager.go:181 +0x8a
github.com/nuts-foundation/nuts-node/network/transport/grpc.(*conn).open.func2(0xc00039b400)
	/home/circleci/project/network/transport/grpc/connection.go:229 +0xa6
github.com/nuts-foundation/nuts-node/network/transport/grpc.(*outboundConnector).start.func1()
	/home/circleci/project/network/transport/grpc/outbound_connector.go:88 +0x454
created by github.com/nuts-foundation/nuts-node/network/transport/grpc.(*outboundConnector).start
	/home/circleci/project/network/transport/grpc/outbound_connector.go:71 +0x16c
FAIL	github.com/nuts-foundation/nuts-node/network	11.900s
```

Suggesting an open stream is called after the connection manager is being stopped...

**Comment by dmeijboom** [comment]
Still happens: https://app.circleci.com/pipelines/github/nuts-foundation/nuts-node/2350/workflows/b87889d3-e968-47ad-b3a4-0bea1f776e20/jobs/2542

**Comment by woutslakhorst** [comment]
@reinkrul @dmeijboom after refactor of network, still happening?

**Comment by reinkrul** [comment]
Should be fixed now.
