### ISSUE TITLE
Network: v2 protocol unit test sometimes fails on CircleCI

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/nuts-node#875]
```
time="2022-03-14T14:58:23Z" level=info msg="Discovered Nuts node (address=peer:5555), published by did:nuts:peer" module=Network
FAIL
coverage: 74.4% of statements
FAIL	github.com/nuts-foundation/nuts-node/network	22.650s
panic: sync: negative WaitGroup counter

goroutine 46 [running]:
sync.(*WaitGroup).Add(0xc00030cd14, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:74 +0x278
sync.(*WaitGroup).Done(...)
	/usr/local/go/src/sync/waitgroup.go:99
github.com/nuts-foundation/nuts-node/network/transport/v2/gossip.TestManager_PeerDisconnected.func3.1({0xc00030b2c0, 0x47cd75}, {0x410820, 0x7f6fc3780008, 0xc00030b2d8})
	/home/circleci/project/network/transport/v2/gossip/manager_test.go:107 +0x91
github.com/nuts-foundation/nuts-node/network/transport/v2/gossip.callSenders.func1()
	/home/circleci/project/network/transport/v2/gossip/manager.go:134 +0x130
github.com/nuts-foundation/nuts-node/network/transport/v2/gossip.(*peerQueue).do(0xc00030b2c0, 0xc00037d6d8)
	/home/circleci/project/network/transport/v2/gossip/queue.go:70 +0xa7
github.com/nuts-foundation/nuts-node/network/transport/v2/gossip.callSenders({0xd86acd, 0x1}, 0xc00030b2c0, {0xc00031c060, 0x1, 0x1})
	/home/circleci/project/network/transport/v2/gossip/manager.go:129 +0xcf
github.com/nuts-foundation/nuts-node/network/transport/v2/gossip.(*manager).PeerConnected.func1()
	/home/circleci/project/network/transport/v2/gossip/manager.go:122 +0xf7
created by github.com/nuts-foundation/nuts-node/network/transport/v2/gossip.(*manager).PeerConnected
	/home/circleci/project/network/transport/v2/gossip/manager.go:113 +0x559
FAIL	github.com/nuts-foundation/nuts-node/network/transport/v2/gossip	0.294s
```

**Comment by woutslakhorst** [comment]
> CircleCI seems to be slow now and then, maybe due to a time-out?

Then a test failure should occur as well
